const GAMES = [

{ id:'hunt', name:'Treasure Hunt', emoji:'🔎', energy:'calm', hue:'#3DDC97', kind:'std',
  how:'Read the card, then ask: "Can you find something like this?" Pointing counts, touching is bonus (when it\u2019s okay to touch). Everybody hunts \u2014 grown-ups too.',
  cards:[
    {e:'🌵', k:'Find something SPIKY!', p:'Pokey plants, spiky hair, fence tips, a pineapple on a shirt\u2026'},
    {e:'🐊', k:'Find something BUMPY!', p:'Brick walls, tire treads, textured floors, goosebumps count.'},
    {e:'🪞', k:'Find something SMOOTH!', p:'Glass, railings, phone screens, a slide.'},
    {e:'🧸', k:'Find something SOFT!', p:'Stuffies, sweaters, hair, a fluffy dog (ask before petting!).'},
    {e:'🪨', k:'Find something HARD!', p:'Knock-knock test: if it goes tap-tap, it counts.'},
    {e:'✨', k:'Find something SHINY!', p:'Jewelry, keys, windows, car paint, a puddle.'},
    {e:'🐑', k:'Find something FUZZY!', p:'Fleece, pom-poms, fuzzy socks, a beard.'},
    {e:'🍮', k:'Find something SQUISHY!', p:'A backpack, a water bottle, cheeks (their own!).'},
    {e:'⚪', k:'Find something ROUND!', p:'Wheels, buttons, clocks, heads, the sun (no staring).'},
    {e:'📐', k:'Find something POINTY!', p:'Roof corners, arrows on signs, shoe tips, a nose?'},
    {e:'🦓', k:'Find some STRIPES!', p:'Shirts, crosswalks, awnings, flags.'},
    {e:'🐞', k:'Find some SPOTS or DOTS!', p:'Polka dots, freckles, signs with dots, a dalmatian if you\u2019re lucky.'},
    {e:'🐜', k:'Find something TINY!', p:'Smaller than your pinky nail. Ants, crumbs, tiny letters.'},
    {e:'🐘', k:'Find something HUGE!', p:'Bigger than a grown-up. Buildings, trucks, trees.'},
    {e:'🍎', k:'Find something RED!', p:'Signs, shirts, shoes, exit signs are a freebie.'},
    {e:'🫐', k:'Find something BLUE!', p:'Jeans count \u2014 but only someone else\u2019s after the first time.'},
    {e:'🥦', k:'Find something GREEN!', p:'Plants, signs, green shirts, a green light.'},
    {e:'🌟', k:'Find something YELLOW!', p:'Warning signs, taxis, bananas in a bag?'},
    {e:'🍊', k:'Find something ORANGE!', p:'Cones, vests, snacks, sunset if you\u2019re out late.'},
    {e:'🍇', k:'Find something PURPLE!', p:'The rare one! Shirts, hair, candy wrappers.'},
    {e:'🌸', k:'Find something PINK!', p:'Flowers, shoes, sunburned noses.'},
    {e:'🐻', k:'Find something BROWN!', p:'Boxes, hair, coffee cups, tree trunks.'},
    {e:'⬛', k:'Find something BLACK!', p:'Phones, shoes, tires \u2014 too easy? Find THREE.'},
    {e:'⬜', k:'Find something WHITE!', p:'Clouds, socks, paper, teeth (show me!).'},
    {e:'⭕', k:'Find a CIRCLE!', p:'Look up, look down \u2014 circles hide everywhere.'},
    {e:'🔺', k:'Find a TRIANGLE!', p:'Roofs, yield signs, pizza slices, folded napkins.'},
    {e:'🟦', k:'Find a SQUARE!', p:'Windows, tiles, boxes, phone apps.'},
    {e:'⭐', k:'Find a STAR!', p:'On clothes, flags, signs, shoes. Trickier than it sounds!'},
    {e:'❤️', k:'Find a HEART!', p:'Logos, jewelry, stickers \u2014 or make one with your hands.'},
    {e:'🛞', k:'Find something with WHEELS!', p:'Strollers, carts, suitcases, skateboards, cars.'},
    {e:'🔔', k:'Find something that makes NOISE!', p:'Then make its sound together, quietly.'},
    {e:'🧢', k:'Find something you could WEAR!', p:'That isn\u2019t already being worn by you two.'},
    {e:'🔤', k:'Find a LETTER!', p:'On a sign or shirt. Bonus: a letter from their name!'},
    {e:'🔢', k:'Find a NUMBER!', p:'Prices, signs, doors. Bonus: their age!'},
    {e:'🐕', k:'Find an ANIMAL!', p:'Real OR a picture \u2014 logos and shirts count.'},
    {e:'🦒', k:'Find something TALLER than me!', p:'Then something shorter than the kiddo. Then something in between!'},
  ]},

{ id:'ispy', name:'I Spy', emoji:'👁️', energy:'calm', hue:'#4CC9F0', kind:'std',
  how:'Secretly pick something you can BOTH see that matches the card. Say the magic words \u2014 "I spy with my little eye\u2026" \u2014 and let them guess until they find it. Then swap: they spy, you guess (badly, for laughs).',
  cards:[
    {e:'🍓', k:'I spy\u2026 something RED', p:'Say: "I spy with my little eye, something RED." Wrong guesses get a "nooope!"'},
    {e:'🐳', k:'I spy\u2026 something BLUE', p:'Pick something they\u2019ll find with a little effort \u2014 not their own shirt.'},
    {e:'🐸', k:'I spy\u2026 something GREEN', p:'Give warmer/colder hints if they stall out.'},
    {e:'🌻', k:'I spy\u2026 something YELLOW', p:'Their turn next \u2014 even if they pick something behind your head.'},
    {e:'⬆️', k:'I spy\u2026 something UP HIGH', p:'Above everyone\u2019s heads. Lights, signs, ceilings, birds.'},
    {e:'⬇️', k:'I spy\u2026 something DOWN LOW', p:'Below your knees. Shoes, wheels, cracks, gum (ew).'},
    {e:'💨', k:'I spy\u2026 something that MOVES', p:'Fans, flags, doors, people, escalators.'},
    {e:'🪑', k:'I spy\u2026 something you can SIT on', p:'Benches, ledges, strollers \u2014 shoulders count.'},
    {e:'☁️', k:'I spy\u2026 something SOFT', p:'They may need to guess by looking, not touching.'},
    {e:'🔵', k:'I spy\u2026 something ROUND', p:'Circles are everywhere once you start looking.'},
    {e:'👄', k:'I spy\u2026 something that starts with "mmm"', p:'Say the SOUND, not the letter: "something that starts with mmm." Sneaky phonics!'},
    {e:'✋', k:'I spy\u2026 something the size of your HAND', p:'They can hold their hand up to check candidates from afar.'},
  ]},

{ id:'count', name:'Count It!', emoji:'🧮', energy:'calm', hue:'#FFC93C', kind:'std',
  how:'Read the card and count together \u2014 point at each one as you go. Little ones: count to 5 and celebrate. Big ones: keep going and try to beat the card next time.',
  cards:[
    {e:'👟', k:'Count the SHOES!', p:'Just the ones you can see without moving. Boots count double? Your call.'},
    {e:'🧢', k:'Count the HATS!', p:'Caps, beanies, hoods that are up \u2014 hunt for them.'},
    {e:'🚪', k:'Count the DOORS!', p:'Big doors, little doors, secret staff doors.'},
    {e:'🪧', k:'Count the SIGNS!', p:'Anything with words or symbols on it.'},
    {e:'💡', k:'Count the LIGHTS!', p:'Look up! Then count how many are actually on.'},
    {e:'👓', k:'Count people wearing GLASSES!', p:'Sunglasses count. Glasses on heads count.'},
    {e:'🛞', k:'Count the WHEELS!', p:'Strollers, carts, suitcases. This one gets big fast.'},
    {e:'🌳', k:'Count the TREES or PLANTS!', p:'Real or fake \u2014 fake ones are worth a giggle.'},
    {e:'🪟', k:'Count the WINDOWS!', p:'If there are tons, count just one wall.'},
    {e:'🔘', k:'Count YOUR buttons!', p:'On both your outfits. Zippers count as one.'},
    {e:'👖', k:'Count YOUR pockets!', p:'Check everywhere \u2014 secret pockets are the best find.'},
    {e:'📱', k:'Count grown-ups on PHONES!', p:'Count the grown-ups staring at their phones. (No judgment. Put yours down after.)'},
    {e:'🧒', k:'Count the KIDS!', p:'How many kids besides you? Babies count!'},
    {e:'😊', k:'Count the SMILES!', p:'Only ones you can see right now \u2014 so go make some happen.'},
  ]},

{ id:'animals', name:'Animal Clues', emoji:'🦁', energy:'calm', hue:'#FF9F43', kind:'reveal',
  how:'Read the clues one at a time \u2014 pause for guesses after each. Start mysterious, get obvious. When they get it (or give up dramatically), tap Reveal and celebrate. Don\u2019t let them peek!',
  cards:[
    {e:'🐘', name:'an ELEPHANT!', clues:['I am very, very big and gray.','My nose is so long I can pick things up with it.','I have giant flappy ears. Toot toot!']},
    {e:'🐶', name:'a DOG!', clues:['I am furry and I love people.','I wag my tail when I\u2019m happy.','I say WOOF WOOF!']},
    {e:'🐱', name:'a CAT!', clues:['I am soft and very sneaky.','I love to chase mice and nap in the sun.','I say MEOW.']},
    {e:'🦁', name:'a LION!', clues:['I am a very big cat.','I have big fluffy hair around my head called a mane.','I say ROOOAAAR!']},
    {e:'🐵', name:'a MONKEY!', clues:['I love to climb and swing in trees.','My favorite snack is a banana.','I say ooh-ooh-ah-ah!']},
    {e:'🐸', name:'a FROG!', clues:['I am small and green.','I hop-hop-hop on lily pads.','I say RIBBIT!']},
    {e:'🐮', name:'a COW!', clues:['I live on a farm and eat grass.','Milk comes from me!','I say MOOOO.']},
    {e:'🦆', name:'a DUCK!', clues:['I can swim AND fly.','I waddle when I walk.','I say QUACK QUACK!']},
    {e:'🐍', name:'a SNAKE!', clues:['I have no legs at all.','I slither on the ground.','I say ssssssss\u2026']},
    {e:'🐰', name:'a BUNNY!', clues:['I have two looong ears.','I hop everywhere I go.','I love to munch on carrots!']},
    {e:'🦉', name:'an OWL!', clues:['I stay awake all night.','I have big, big round eyes.','I say WHOO! WHOO!']},
    {e:'🐧', name:'a PENGUIN!', clues:['I am a bird, but I cannot fly.','I am black and white and I love the cold.','I waddle-waddle on the ice!']},
    {e:'🦒', name:'a GIRAFFE!', clues:['I am the tallest animal of all.','My neck is looooong so I can reach the treetops.','I have orange and brown patches.']},
    {e:'🐝', name:'a BEE!', clues:['I am teeny tiny with wings.','I visit flowers and make honey.','I say BZZZZZ!']},
    {e:'🦖', name:'a DINOSAUR!', clues:['I lived a long, long, LONG time ago.','I had giant teeth and tiny arms.','I go STOMP STOMP ROAR!']},
    {e:'🐠', name:'a FISH!', clues:['I live underwater.','I have no legs \u2014 I have fins!','I go blub, blub, blub.']},
  ]},

{ id:'name5', name:'Name 5', emoji:'🖐️', energy:'calm', hue:'#9B5DE5', kind:'std',
  how:'Read the category. They name 5 things that fit \u2014 hold up a finger for each one. Stuck at 3? Team up and finish together. High five when the hand is full!',
  cards:[
    {e:'🐾', k:'Name 5 ANIMALS!', p:'Any animals at all. Made-up sounds earn bonus points.'},
    {e:'🍎', k:'Name 5 FOODS!', p:'Then ask: which one should we eat after this?'},
    {e:'🍭', k:'Name 5 YUMMY TREATS!', p:'Prepare for a snack request. You brought this on yourself.'},
    {e:'🌊', k:'Name 5 things in the OCEAN!', p:'Fish, whales, mermaids \u2014 all accepted.'},
    {e:'🚜', k:'Name 5 things with WHEELS!', p:'Fingers up! Bikes, trucks, strollers\u2026'},
    {e:'🪽', k:'Name 5 things that FLY!', p:'Birds, planes, superheroes, balloons\u2026'},
    {e:'🐄', k:'Name 5 FARM animals!', p:'Make each one\u2019s sound as you count it.'},
    {e:'🧊', k:'Name 5 COLD things!', p:'Ice cream, snow, popsicles, penguins\u2026'},
    {e:'🔥', k:'Name 5 HOT things!', p:'Careful things! The sun, soup, lava\u2026'},
    {e:'🛏️', k:'Name 5 things in your BEDROOM!', p:'Can they picture their room from here?'},
    {e:'📣', k:'Name 5 things that make NOISE!', p:'Demonstrations encouraged, at whisper volume.'},
    {e:'🐋', k:'Name 5 things BIGGER than you!', p:'Then: 5 things smaller than your pinky.'},
  ]},

{ id:'wyr', name:'Would You Rather', emoji:'🤔', energy:'calm', hue:'#F15BB5', kind:'choice',
  pDefault:'Read both choices out loud. Everyone picks \u2014 then ask the magic question: "WHY?" Silly answers only. There are no wrong answers.',
  how:'Read both options with maximum drama. Everyone answers \u2014 grown-ups too \u2014 and then everyone asks each other WHY. The why is where it gets good.',
  cards:[
    {a:['🐒','a monkey tail'], b:['🪽','bird wings']},
    {a:['🐭','be TINY as a mouse'], b:['🏔️','be HUGE as a giant']},
    {a:['🍦','eat only ice cream forever'], b:['🍕','eat only pizza forever']},
    {a:['🦖','a pet dinosaur'], b:['🐉','a pet dragon']},
    {a:['🌳','live in a treehouse'], b:['🏰','live in a castle']},
    {a:['🕊️','be able to FLY'], b:['👻','turn INVISIBLE']},
    {a:['🐾','talk to animals'], b:['🧸','talk to your toys']},
    {a:['🦘','bounce like a kangaroo'], b:['🐬','swim like a dolphin']},
    {a:['🍝','hair made of spaghetti'], b:['🌱','hair made of grass']},
    {a:['❄️','snow every day'], b:['☀️','sunshine every day']},
    {a:['🦄','ride a unicorn'], b:['🚀','ride a rocket']},
    {a:['✨','sneeze GLITTER'], b:['🫧','burp BUBBLES']},
    {a:['🦸','be a superhero'], b:['🧙','be a wizard']},
    {a:['🐶','have 100 puppies'], b:['🐱','have 100 kittens']},
  ]},

{ id:'story', name:'Story Starters', emoji:'📖', energy:'calm', hue:'#5271FF', kind:'std',
  how:'Read the starter with your best storyteller voice, then take turns: one sentence each. When they pause, ask "and THEN what happened?!" The story ends whenever you reach the front of the line \u2014 or when everyone is giggling too hard.',
  cards:[
    {e:'🐉', k:'The Hungry Little Dragon', p:'Say: "Once upon a time, a tiny dragon was SO hungry\u2026 but the only thing left to eat was\u2026" \u2014 their turn!'},
    {e:'👟', k:'The Runaway Shoes', p:'Say: "One morning, all the shoes in the house ran away, because\u2026"'},
    {e:'🧑\u200d🚀', k:'The Little Astronaut', p:'Say: "A little astronaut landed on a planet made ENTIRELY of\u2026"'},
    {e:'👾', k:'The Friendly Monster', p:'Say: "The monster under the bed wasn\u2019t scary at all. It just really, really wanted\u2026"'},
    {e:'🦴', k:'The Magic Bone', p:'Say: "A puppy dug up a magic bone. Whoever held it could suddenly\u2026"'},
    {e:'🍦', k:'Ice Cream Truck on the Moon', p:'Say: "The ice cream truck got a flat tire\u2026 ON THE MOON! So\u2026"'},
    {e:'🚪', k:'The Door in the Tree', p:'Say: "Behind a tiny door in a big old tree, there was\u2026"'},
    {e:'🦸', k:'The Silliest Superhero', p:'Say: "The silliest superhero in the world had one power: they could\u2026"'},
    {e:'🌧️', k:'Raining Spaghetti', p:'Say: "One day it started to rain\u2026 SPAGHETTI! Everyone grabbed\u2026"'},
    {e:'🐭', k:'The Mouse Who Wanted to Be Big', p:'Say: "A tiny mouse wished to be as big as an elephant. So she\u2026"'},
    {e:'🍪', k:'The Cookies Come Alive', p:'Say: "At midnight, Grandma\u2019s cookies woke up and decided to\u2026"'},
    {e:'🐜', k:'Shrunk Down Small', p:'Say: "We shrank down as small as ants! Our shoe became our house, and\u2026"'},
  ]},

{ id:'sounds', name:'Sound Detective', emoji:'👂', energy:'calm', hue:'#00B8A9', kind:'std',
  how:'Whisper: "Detective ears\u2026 ON!" Close your eyes (or just look down at your shoes) and listen hard for what\u2019s on the card. Great for calming a wound-up kiddo in a loud place.',
  cards:[
    {e:'📢', k:'Listen for something LOUD', p:'Point (eyes still closed!) toward where it came from.'},
    {e:'🤫', k:'Listen for the QUIETEST sound', p:'You have to get really still for this one. That\u2019s the point.'},
    {e:'🗣️', k:'Listen for a VOICE', p:'Can you hear what they\u2019re saying? Is it a kid or a grown-up?'},
    {e:'🎵', k:'Listen for MUSIC', p:'No music playing? Hum a tiny bit and see how fast they catch you.'},
    {e:'🛎️', k:'Listen for a BEEP or a DING', p:'Registers, phones, doors, trucks backing up.'},
    {e:'👣', k:'Listen for FOOTSTEPS', p:'Fast ones or slow ones? Big feet or little feet?'},
    {e:'🚗', k:'Listen for something with an ENGINE', p:'Car, truck, bus, plane \u2014 which one was it?'},
    {e:'🐦', k:'Listen for a BIRD', p:'Outside only \u2014 or is it? Some stores have sneaky sparrows.'},
    {e:'😄', k:'Listen for LAUGHING', p:'If you can\u2019t find any\u2026 make some.'},
    {e:'🔢', k:'Count the DIFFERENT sounds', p:'Eyes closed, ten seconds, fingers up for each new sound. Compare totals!'},
    {e:'🤖', k:'What\u2019s making the WEIRDEST sound?', p:'Find the strangest sound you can hear, then invent what\u2019s REALLY making it. A robot? A dragon snoring?'},
  ]},

{ id:'rhyme', name:'Rhyme Time', emoji:'🎤', energy:'calm', hue:'#D96BFF', kind:'std',
  how:'Say the word on the card. Take turns saying words that rhyme with it \u2014 real words OR silly made-up ones. Can\u2019t think of one? Say it in a robot voice and try again. Keep going until you both run dry, then flip the card.',
  cards:[
    {e:'🐱', k:'CAT', p:'Hat, bat, mat, sat, rat\u2026 splat!'},
    {e:'🐶', k:'DOG', p:'Frog, log, jog, fog\u2026 bog!'},
    {e:'🐝', k:'BEE', p:'Tree, see, me, key, three!'},
    {e:'⭐', k:'STAR', p:'Car, far, jar\u2026 are!'},
    {e:'🎂', k:'CAKE', p:'Lake, snake, shake, rake\u2026 mistake!'},
    {e:'⚽', k:'BALL', p:'Tall, small, wall, fall, hall!'},
    {e:'🐭', k:'MOUSE', p:'House, blouse\u2026 this one runs out fast, so silly words save the day.'},
    {e:'🐛', k:'BUG', p:'Hug, rug, mug, tug\u2026 glug!'},
    {e:'🌙', k:'MOON', p:'Spoon, soon, noon, balloon!'},
    {e:'🧦', k:'SOCK', p:'Rock, block, clock, knock-knock!'},
    {e:'🚂', k:'TRAIN', p:'Rain, brain, chain, plane!'},
    {e:'🐷', k:'PIG', p:'Big, dig, wig, fig\u2026 jig! (Do the jig.)'},
  ]},

{ id:'simon', name:'Simon Says', emoji:'🫡', energy:'active', hue:'#FF6B6B', kind:'std',
  how:'You\u2019re Simon! Read each card out loud EXACTLY as written. If it starts with "Simon says," they do it. If it doesn\u2019t \u2014 they should freeze! Got tricked? Giggle and keep playing. With very little ones, skip the tricks and just do the moves together.',
  cards:[
    {e:'👃', k:'Touch your nose', p:'Say: "Simon says\u2026 touch your nose!"'},
    {e:'🦶', k:'Touch your toes', p:'Say: "Simon says\u2026 touch your toes!"'},
    {e:'🙌', k:'Hands on your head', p:'Say: "Simon says\u2026 put your hands on your head!"', trick:false},
    {e:'🐇', k:'Hop 3 times', p:'Say: "Simon says\u2026 hop three times!" Tiny hops \u2014 we\u2019re in a line.'},
    {e:'🪼', k:'Wiggle like jelly', p:'Say: "Simon says\u2026 wiggle like jelly!"'},
    {e:'🗿', k:'Freeze like a statue', p:'Say: "Simon says\u2026 freeze like a statue!" See how long they last.'},
    {e:'👀', k:'Blink super fast', p:'Say: "Simon says\u2026 blink as fast as you can!"'},
    {e:'😝', k:'Stick out your tongue', p:'TRICK! Say just: "Stick out your tongue!" \u2014 did they freeze, or are you looking at a tongue?', trick:true},
    {e:'🙆', k:'Arms up high', p:'Say: "Simon says\u2026 reach up as high as you can!"'},
    {e:'👏', k:'Three tiny claps', p:'Say: "Simon says\u2026 do three tiny quiet claps!"'},
    {e:'🥾', k:'Stomp softly', p:'TRICK! Say just: "Stomp your feet!" \u2014 freeze check!', trick:true},
    {e:'🔄', k:'Turn around once', p:'Say: "Simon says\u2026 turn around one time!"'},
    {e:'🤪', k:'Make a silly face', p:'Say: "Simon says\u2026 make your silliest face!" You have to make one back.'},
    {e:'🐔', k:'Flap like a chicken', p:'TRICK! Say just: "Flap your wings!" \u2014 anyone flapping is a chicken.', trick:true},
    {e:'👍', k:'Thumbs up', p:'Say: "Simon says\u2026 give me a thumbs up!"'},
    {e:'🤫', k:'Whisper your name', p:'Say: "Simon says\u2026 whisper your name as quietly as you can."'},
    {e:'😁', k:'Biggest smile', p:'TRICK! Say just: "Smile really big!" \u2014 nobody can resist this one. Gotcha.', trick:true},
    {e:'👂', k:'Touch your ears', p:'Say: "Simon says\u2026 touch your ears!"'},
    {e:'🦩', k:'Stand on one foot', p:'Say: "Simon says\u2026 stand on one foot like a flamingo!"'},
    {e:'🫲', k:'Shake my hand', p:'TRICK! Say just: "Shake my hand!" while offering it. Diabolical. Shake anyway if they fall for it.', trick:true},
  ]},

{ id:'freeze', name:'Freeze!', emoji:'🧊', energy:'active', hue:'#4CC9F0', kind:'std',
  how:'Say "WIGGLE WIGGLE WIGGLE!" \u2014 everyone wiggle-dances in place. Then call "FREEZE!" and show the card: hold that pose while you count to five. Wobbling means giggling means go again. Pretending to BE the thing helps them hold still way longer.',
  cards:[
    {e:'⭐', k:'Freeze like a STAR', p:'Arms and legs out wide. Count to 5 \u2014 slower each round.'},
    {e:'🦩', k:'Freeze like a FLAMINGO', p:'One foot up! Grab a shoulder if the floor is lava-wobbly.'},
    {e:'🦸', k:'Freeze like a SUPERHERO', p:'Fists on hips, chin up, cape imaginary.'},
    {e:'🤖', k:'Freeze like a ROBOT', p:'Stiff arms, square angles. Powering down\u2026 beep\u2026 boop\u2026'},
    {e:'😴', k:'Freeze like a SLEEPING CAT', p:'Standing up! Paw-hands, eyes closed, one tiny fake snore allowed.'},
    {e:'🩰', k:'Freeze like a BALLERINA', p:'Up on tippy-toes, arms in a circle. Hardest one!'},
    {e:'🦍', k:'Freeze like a GORILLA', p:'Big arms, knuckles low, mid chest-thump. Silent roar face.'},
    {e:'🌳', k:'Freeze like a TREE', p:'Arms are branches. A gentle breeze may sway you\u2026 but just barely.'},
    {e:'🍝', k:'Freeze like SPAGHETTI', p:'First wiggle like cooked spaghetti\u2026 then FREEZE stiff like uncooked spaghetti!'},
    {e:'🏄', k:'Freeze like a SURFER', p:'Knees bent, arms out, riding an invisible wave.'},
    {e:'💪', k:'Freeze like a STRONG-PERSON', p:'Double arm flex. Grrr face required.'},
    {e:'🐭', k:'Freeze like a TINY MOUSE', p:'Crouch small-small-small. Whisker hands. Squeak once, then silence.'},
  ]},

{ id:'walks', name:'Silly Walks', emoji:'🐧', energy:'active', hue:'#7BC950', kind:'std',
  how:'This one is FOR when the line moves! Each time you shuffle forward, walk to the next spot the way the card says. When the line stops \u2014 freeze in character until it moves again. The waiting becomes the game.',
  cards:[
    {e:'🤖', k:'Walk like a ROBOT', p:'Stiff legs, stiff arms. Beep with each step.'},
    {e:'🥷', k:'Sneak like a NINJA', p:'Silent tippy-toes. If anyone hears you, you must start again.'},
    {e:'🐧', k:'Waddle like a PENGUIN', p:'Feet together, arms flat at your sides, waddle-waddle.'},
    {e:'🦣', k:'Stomp like a GIANT', p:'Giant SLOW steps \u2014 soft stomps, we\u2019re being polite giants.'},
    {e:'🐭', k:'Scurry like a MOUSE', p:'Teeny-tiny fast steps. How many tiny steps to the next spot?'},
    {e:'🥁', k:'March like a DRUMMER', p:'Knees up! Pat the drum-beat on your legs as you march.'},
    {e:'🧑\u200d🚀', k:'Moon-walk like an ASTRONAUT', p:'Slooow bouncy steps. There\u2019s no gravity in this line.'},
    {e:'🦀', k:'Scuttle like a CRAB', p:'Side-steps only! Pinchy claw hands.'},
    {e:'🦥', k:'Creep like a SLOTH', p:'The sloooowest walk ever. Perfect for a slow line.'},
    {e:'🐰', k:'Hop like a BUNNY', p:'Little hops, paws up. Nose wiggles at each stop.'},
    {e:'👑', k:'Strut like ROYALTY', p:'Nose in the air, tiny fancy steps, royal wave at your subjects.'},
    {e:'🧟', k:'Shuffle like a ZOMBIE', p:'Arms out, dragging feet, quiet "braaains\u2026" (or "snaaacks\u2026").'},
    {e:'🦖', k:'Stomp like a T-REX', p:'Tiny arms tucked in, big soft stomps, one small roar.'},
    {e:'🎪', k:'Walk the TIGHTROPE', p:'Heel-to-toe on an imaginary rope. Arms out for balance \u2014 don\u2019t fall in the crocodile pit!'},
  ]},

{ id:'copycat', name:'Copycat', emoji:'🪞', energy:'active', hue:'#FF8FA3', kind:'std',
  how:'Do what the card says \u2014 kiddo copies you exactly. Then SWAP: they invent, you copy (mess it up a little; being copied badly is hilarious). Add speed for extra giggles.',
  cards:[
    {e:'👏', k:'Copy the CLAPS', p:'Clap a pattern: clap-clap-STOMP. They echo it. Make it one beat longer each round.'},
    {e:'🪞', k:'Slow-motion MIRROR', p:'Face each other. Move super slowly \u2014 they mirror you like a reflection. Then swap leaders.'},
    {e:'🤪', k:'Funny face contest', p:'Make a face, they copy it. Take turns. No laughing\u2026 impossible.'},
    {e:'🤯', k:'Pat head, rub tummy', p:'Both at once! Then swap hands. Then\u2026 while balancing on one foot?'},
    {e:'⚡', k:'Head-shoulders-knees-toes', p:'Once slow, once medium, once LUDICROUS SPEED.'},
    {e:'😉', k:'Wink practice', p:'Wink one eye, then the other. Little kids\u2019 double-blink attempts are the best thing you\u2019ll see all day.'},
    {e:'🥁', k:'Air drums', p:'Play an invisible drum solo. They copy your solo, then perform their own. Nod respectfully.'},
    {e:'🤨', k:'Eyebrow wiggles', p:'Wiggle your eyebrows. Can they do one at a time? Can YOU?'},
    {e:'🖐️', k:'Slow-motion high five', p:'The slowest high five in history. Dramatic wind-up. Gentle landing. "Niiiiice."'},
    {e:'🎾', k:'Sound Ball', p:'Pretend-throw a ball while making a silly sound \u2014 "BOING!" They catch it making the SAME sound, then throw it back with a NEW sound.'},
    {e:'🧺', k:'The Picnic Game', p:'Say: "I\u2019m going on a picnic and bringing\u2026 apples." They repeat the list and add one thing. How long can the list get?'},
    {e:'🕺', k:'Copy the dance move', p:'One move at a time: spin, wiggle, point. String them into a tiny line-dance routine.'},
  ]},

{ id:'hands', name:'Hand Games', emoji:'✋', energy:'active', hue:'#FFB627', kind:'std',
  how:'Every card is a tiny hand game \u2014 perfect for staying put. Read the card and play right there. Hands only, feet optional, giggles guaranteed.',
  cards:[
    {e:'✊', k:'Rock, Paper, Scissors', p:'"Rock, paper, scissors\u2026 SHOOT!" ✊ crushes ✌️, ✌️ cuts ✋, ✋ wraps ✊. Best of three. Littles can just copy your hand \u2014 that\u2019s a win too.'},
    {e:'👍', k:'Thumb War', p:'Hook fingers: "1, 2, 3, 4 \u2014 I declare a thumb war!" Pin their thumb for a count of 3. Lose dramatically.'},
    {e:'🖐️', k:'Hand Stack', p:'Stack all your hands in a tower. Bottom hand flies to the top. Faster\u2026 faster\u2026 until it collapses!'},
    {e:'🤝', k:'Invent a Secret Handshake', p:'Take turns adding ONE move at a time: fist bump\u2026 then wiggle\u2026 then elbow tap\u2026 How many moves can you both remember?'},
    {e:'🖐', k:'Up High, Down Low', p:'"Up high! Down low!\u2026 TOO SLOW!" Then let them get you back. Always let them get you back.'},
    {e:'👏', k:'Echo Claps', p:'Clap a rhythm \u2014 they clap it back like an echo. Start with 2 claps, build up. Then they lead.'},
    {e:'🔢', k:'Finger Flash', p:'"Show me 3 fingers! Now 5! Now 1! Now 4!" Faster and faster. Then swap: they call, you flash (get one wrong on purpose).'},
    {e:'🫸', k:'Sticky Hands', p:'Press your palms together with theirs. "Oh no\u2026 they\u2019re STUCK! 1\u2026 2\u2026 3\u2026 UNSTICK!" Fling apart dramatically.'},
    {e:'🕷️', k:'Itsy Bitsy Spider', p:'The classic finger play: spider climbs up, rain washes it out, sun comes up, spider climbs again. Perfect for the littlest waiters.'},
    {e:'🧸', k:'Round and Round the Garden', p:'Trace a slow circle on their palm: "Round and round the garden, like a teddy bear\u2026 one step, two step\u2026 TICKLE under there!"'},
  ]},

];
