const GAMES = [

{ id:'hunt', name:'Treasure Hunt', emoji:'🔎', energy:'calm', hue:'#3DDC97', kind:'std',
  how:'Read the card, then ask: "Can you find something like this?" Pointing counts, touching is bonus (when it\u2019s okay to touch). Everybody hunts \u2014 grown-ups too.',
  cards:[
    {e:'🌵', k:'Find something SPIKY!', p:'Pokey plants, spiky hair, fence tips, a pineapple on a shirt\u2026'},
    {e:'🐊', k:'Find something BUMPY!', p:'Brick walls, tire treads, textured floors, goosebumps count.'},
    {e:'🪞', k:'Find something SMOOTH!', p:'Glass, railings, phone screens, a slide.'},
    {e:'🧸', k:'Find something SOFT!', p:'Stuffies, sweaters, hair, a fluffy dog (ask before petting!).'},
    {e:'🪨', k:'Find something HARD!', p:'Knock-knock test: if it goes tap-tap, it counts.'},
    {e:'✨', k:'Find something SHINY!', p:'Jewelry, keys, windows, car paint, a puddle.'},
    {e:'🐑', k:'Find something FUZZY!', p:'Fleece, pom-poms, fuzzy socks, a beard.'},
    {e:'🍮', k:'Find something SQUISHY!', p:'A backpack, a water bottle, cheeks (their own!).'},
    {e:'⚪', k:'Find something ROUND!', p:'Wheels, buttons, clocks, heads, the sun (no staring).'},
    {e:'📐', k:'Find something POINTY!', p:'Roof corners, arrows on signs, shoe tips, a nose?'},
    {e:'🦓', k:'Find some STRIPES!', p:'Shirts, crosswalks, awnings, flags.'},
    {e:'🐞', k:'Find some SPOTS or DOTS!', p:'Polka dots, freckles, signs with dots, a dalmatian if you\u2019re lucky.'},
    {e:'🐜', k:'Find something TINY!', p:'Smaller than your pinky nail. Ants, crumbs, tiny letters.'},
    {e:'🐘', k:'Find something HUGE!', p:'Bigger than a grown-up. Buildings, trucks, trees.'},
    {e:'🍎', k:'Find something RED!', p:'Signs, shirts, shoes, exit signs are a freebie.'},
    {e:'🫐', k:'Find something BLUE!', p:'Jeans count \u2014 but only someone else\u2019s after the first time.'},
    {e:'🥦', k:'Find something GREEN!', p:'Plants, signs, green shirts, a green light.'},
    {e:'🌟', k:'Find something YELLOW!', p:'Warning signs, taxis, bananas in a bag?'},
    {e:'🍊', k:'Find something ORANGE!', p:'Cones, vests, snacks, sunset if you\u2019re out late.'},
    {e:'🍇', k:'Find something PURPLE!', p:'The rare one! Shirts, hair, candy wrappers.'},
    {e:'🌸', k:'Find something PINK!', p:'Flowers, shoes, sunburned noses.'},
    {e:'🐻', k:'Find something BROWN!', p:'Boxes, hair, coffee cups, tree trunks.'},
    {e:'⬛', k:'Find something BLACK!', p:'Phones, shoes, tires \u2014 too easy? Find THREE.'},
    {e:'⬜', k:'Find something WHITE!', p:'Clouds, socks, paper, teeth (show me!).'},
    {e:'⭕', k:'Find a CIRCLE!', p:'Look up, look down \u2014 circles hide everywhere.'},
    {e:'🔺', k:'Find a TRIANGLE!', p:'Roofs, yield signs, pizza slices, folded napkins.'},
    {e:'🟦', k:'Find a SQUARE!', p:'Windows, tiles, boxes, phone apps.'},
    {e:'⭐', k:'Find a STAR!', p:'On clothes, flags, signs, shoes. Trickier than it sounds!'},
    {e:'❤️', k:'Find a HEART!', p:'Logos, jewelry, stickers \u2014 or make one with your hands.'},
    {e:'🛞', k:'Find something with WHEELS!', p:'Strollers, carts, suitcases, skateboards, cars.'},
    {e:'🔔', k:'Find something that makes NOISE!', p:'Then make its sound together, quietly.'},
    {e:'🧢', k:'Find something you could WEAR!', p:'That isn\u2019t already being worn by you two.'},
    {e:'🔤', k:'Find a LETTER!', p:'On a sign or shirt. Bonus: a letter from their name!'},
    {e:'🔢', k:'Find a NUMBER!', p:'Prices, signs, doors. Bonus: their age!'},
    {e:'🐕', k:'Find an ANIMAL!', p:'Real OR a picture \u2014 logos and shirts count.'},
    {e:'🦒', k:'Find something TALLER than me!', p:'Then something shorter than the kiddo. Then something in between!'},
    {e:'🧊', k:'Find something COLD!', p:'Your water glass, a metal fork, the window, an ice cube. Touch test!'},
    {e:'🪵', k:'Find something WOODEN!', p:'The table, a chair, chopsticks, a pencil \u2014 knuckle-knock to be sure.'},
    {e:'🍴', k:'Find something made of METAL!', p:'Forks, spoons, the napkin holder, keys, a belt buckle. Cold AND hard \u2014 double points.'},
    {e:'🫙', k:'Find something SEE-THROUGH!', p:'A water glass, a window, a plastic lid, someone\u2019s glasses.'},
    {e:'🍬', k:'Find something CRINKLY!', p:'A straw wrapper, a napkin, a chip bag, a candy wrapper. Give it a squeeze \u2014 did it crinkle?'},
    {e:'🫓', k:'Find something FLAT!', p:'The tabletop, a plate, a menu, a phone, the floor.'},
    {e:'🥖', k:'Find something LONG!', p:'A straw, a fork, a shoelace, someone\u2019s hair.'},
    {e:'🧦', k:'Find TWO of the same!', p:'A matching pair: shoes, eyes, salt AND pepper, chopsticks, your own two hands.'},
    {e:'🙂', k:'Find a FACE!', p:'A real one, a photo, a cartoon on a bottle, a logo, an emoji on a phone.'},
    {e:'🧀', k:'Find something with HOLES!', p:'The top of a salt shaker, a button, a straw, the holes in a cracker.'},
  ]},

{ id:'ispy', name:'I Spy', emoji:'👁️', energy:'calm', hue:'#4CC9F0', kind:'std',
  how:'Secretly pick something you can BOTH see that matches the card. Say the magic words \u2014 "I spy with my little eye\u2026" \u2014 and let them guess until they find it. Then swap: they spy, you guess (badly, for laughs).',
  cards:[
    {e:'🍓', k:'I spy\u2026 something RED', p:'Say: "I spy with my little eye, something RED." Wrong guesses get a "nooope!"'},
    {e:'🐳', k:'I spy\u2026 something BLUE', p:'Pick something they\u2019ll find with a little effort \u2014 not their own shirt.'},
    {e:'🐸', k:'I spy\u2026 something GREEN', p:'Give warmer/colder hints if they stall out.'},
    {e:'🌻', k:'I spy\u2026 something YELLOW', p:'Their turn next \u2014 even if they pick something behind your head.'},
    {e:'⬆️', k:'I spy\u2026 something UP HIGH', p:'Above everyone\u2019s heads. Lights, signs, ceilings, birds.'},
    {e:'⬇️', k:'I spy\u2026 something DOWN LOW', p:'Below your knees. Shoes, wheels, cracks, gum (ew).'},
    {e:'💨', k:'I spy\u2026 something that MOVES', p:'Fans, flags, doors, people, escalators.'},
    {e:'🪑', k:'I spy\u2026 something you can SIT on', p:'Benches, ledges, strollers \u2014 shoulders count.'},
    {e:'☁️', k:'I spy\u2026 something SOFT', p:'They may need to guess by looking, not touching.'},
    {e:'🔵', k:'I spy\u2026 something ROUND', p:'Circles are everywhere once you start looking.'},
    {e:'👄', k:'I spy\u2026 something that starts with "mmm"', p:'Say the SOUND, not the letter: "something that starts with mmm." Sneaky phonics!'},
    {e:'✋', k:'I spy\u2026 something the size of your HAND', p:'They can hold their hand up to check candidates from afar.'},
    {e:'🧻', k:'I spy\u2026 something WHITE', p:'Napkins, plates, salt, socks \u2014 plenty right at the table.'},
    {e:'✨', k:'I spy\u2026 something SHINY', p:'A fork, a spoon, a phone screen, a ring. Tilt it to catch the light.'},
    {e:'🍞', k:'I spy\u2026 something you can EAT', p:'The bread basket is a freebie \u2014 or point at whatever\u2019s on the way.'},
    {e:'🥤', k:'I spy\u2026 something you DRINK from', p:'A cup, a glass, a straw, a water bottle.'},
    {e:'🍽️', k:'I spy\u2026 something on the TABLE', p:'Pick a little one \u2014 a fork, the salt, a crumb \u2014 so they still have to hunt.'},
    {e:'🔠', k:'I spy\u2026 something with WORDS on it', p:'The menu, a sign, a cup, your shirt. Letters are everywhere.'},
    {e:'🐍', k:'I spy\u2026 something that starts with "sss"', p:'Say the SOUND, not the letter. Spoon, straw, sign, salt, sock.'},
    {e:'🦶', k:'I spy\u2026 something that starts with "fff"', p:'Fork, floor, foot, face \u2014 stretch it out, "ffff." Sneaky phonics.'},
    {e:'🧊', k:'I spy\u2026 something COLD', p:'They may have to guess by touch: a drink, the window, an ice cube.'},
  ]},

{ id:'count', name:'Count It!', emoji:'🧮', energy:'calm', hue:'#FFC93C', kind:'std',
  how:'Read the card and count together \u2014 point at each one as you go. Little ones: count to 5 and celebrate. Big ones: keep going and try to beat the card next time.',
  cards:[
    {e:'👟', k:'Count the SHOES!', p:'Just the ones you can see without moving. Boots count double? Your call.'},
    {e:'🧢', k:'Count the HATS!', p:'Caps, beanies, hoods that are up \u2014 hunt for them.'},
    {e:'🚪', k:'Count the DOORS!', p:'Big doors, little doors, secret staff doors.'},
    {e:'🪧', k:'Count the SIGNS!', p:'Anything with words or symbols on it.'},
    {e:'💡', k:'Count the LIGHTS!', p:'Look up! Then count how many are actually on.'},
    {e:'👓', k:'Count people wearing GLASSES!', p:'Sunglasses count. Glasses on heads count.'},
    {e:'🛞', k:'Count the WHEELS!', p:'Strollers, carts, suitcases. This one gets big fast.'},
    {e:'🌳', k:'Count the TREES or PLANTS!', p:'Real or fake \u2014 fake ones are worth a giggle.'},
    {e:'🪟', k:'Count the WINDOWS!', p:'If there are tons, count just one wall.'},
    {e:'🔘', k:'Count YOUR buttons!', p:'On both your outfits. Zippers count as one.'},
    {e:'👖', k:'Count YOUR pockets!', p:'Check everywhere \u2014 secret pockets are the best find.'},
    {e:'📱', k:'Count grown-ups on PHONES!', p:'Count the grown-ups staring at their phones. (No judgment. Put yours down after.)'},
    {e:'🧒', k:'Count the KIDS!', p:'How many kids besides you? Babies count!'},
    {e:'😊', k:'Count the SMILES!', p:'Only ones you can see right now \u2014 so go make some happen.'},
    {e:'🥄', k:'Count the SPOONS!', p:'Just your table first. Then forks. Then knives \u2014 eyes only, please.'},
    {e:'🥤', k:'Count the CUPS!', p:'Every cup and glass on your table. A cozy little 3 or 4 \u2014 a perfect first mission.'},
    {e:'🧂', k:'Count the SHAKERS!', p:'Salt and pepper make an easy, mighty TWO. Big kids: spot shakers on other tables too.'},
    {e:'🪑', k:'Count the CHAIRS!', p:'Start with your own table \u2014 that\u2019s plenty. Booth benches count as two.'},
    {e:'🖼️', k:'Count the PICTURES on the walls!', p:'Paintings, photos, posters, that weird fish. Bonus: what\u2019s hiding inside each one?'},
    {e:'👂', k:'Count YOUR ears!', p:'Two! Then two eyes, two elbows, two thumbs. Everything comes in twos \u2014 everybody wins.'},
    {e:'🧑\u200d🍳', k:'Count the HELPERS!', p:'People carrying plates or trays. Sneak a little wave if one spots you counting.'},
  ]},

{ id:'animals', name:'Animal Clues', emoji:'🦁', energy:'calm', hue:'#FF9F43', kind:'reveal',
  how:'Read the clues one at a time \u2014 pause for guesses after each. Start mysterious, get obvious. When they get it (or give up dramatically), tap Reveal and celebrate. Don\u2019t let them peek!',
  cards:[
    {e:'🐘', name:'an ELEPHANT!', clues:['I am very, very big and gray.','My nose is so long I can pick things up with it.','I have giant flappy ears. Toot toot!']},
    {e:'🐶', name:'a DOG!', clues:['I am furry and I love people.','I wag my tail when I\u2019m happy.','I say WOOF WOOF!']},
    {e:'🐱', name:'a CAT!', clues:['I am soft and very sneaky.','I love to chase mice and nap in the sun.','I say MEOW.']},
    {e:'🦁', name:'a LION!', clues:['I am a very big cat.','I have big fluffy hair around my head called a mane.','I say ROOOAAAR!']},
    {e:'🐵', name:'a MONKEY!', clues:['I love to climb and swing in trees.','My favorite snack is a banana.','I say ooh-ooh-ah-ah!']},
    {e:'🐸', name:'a FROG!', clues:['I am small and green.','I hop-hop-hop on lily pads.','I say RIBBIT!']},
    {e:'🐮', name:'a COW!', clues:['I live on a farm and eat grass.','Milk comes from me!','I say MOOOO.']},
    {e:'🦆', name:'a DUCK!', clues:['I can swim AND fly.','I waddle when I walk.','I say QUACK QUACK!']},
    {e:'🐍', name:'a SNAKE!', clues:['I have no legs at all.','I slither on the ground.','I say ssssssss\u2026']},
    {e:'🐰', name:'a BUNNY!', clues:['I have two looong ears.','I hop everywhere I go.','I love to munch on carrots!']},
    {e:'🦉', name:'an OWL!', clues:['I stay awake all night.','I have big, big round eyes.','I say WHOO! WHOO!']},
    {e:'🐧', name:'a PENGUIN!', clues:['I am a bird, but I cannot fly.','I am black and white and I love the cold.','I waddle-waddle on the ice!']},
    {e:'🦒', name:'a GIRAFFE!', clues:['I am the tallest animal of all.','My neck is looooong so I can reach the treetops.','I have orange and brown patches.']},
    {e:'🐝', name:'a BEE!', clues:['I am teeny tiny with wings.','I visit flowers and make honey.','I say BZZZZZ!']},
    {e:'🦖', name:'a DINOSAUR!', clues:['I lived a long, long, LONG time ago.','I had giant teeth and tiny arms.','I go STOMP STOMP ROAR!']},
    {e:'🐠', name:'a FISH!', clues:['I live underwater.','I have no legs \u2014 I have fins!','I go blub, blub, blub.']},
{e:'🐷', name:'a PIG!', clues:['I am pink and I love to get all muddy.','I have a little curly tail and a flat, snuffly snout.','I roll in the mud and say OINK OINK!']},
{e:'🐴', name:'a HORSE!', clues:['I am big and strong and I can run very fast.','You can ride on my back, and I have a long swishy tail.','I go clippity-clop and say NEIGHHH!']},
{e:'🐑', name:'a SHEEP!', clues:['I live on a farm and I am covered in fluffy wool.','People use my wool to make warm, cozy sweaters.','I nibble the grass and say BAAAA!']},
{e:'🐔', name:'a ROOSTER!', clues:['I live on a farm and it is my job to wake everybody up.','I have a bright red bumpy crown on top of my head.','When the sun comes up I crow COCK-A-DOODLE-DOO!']},
{e:'🐻', name:'a BEAR!', clues:['I am big and furry and I live deep in the woods.','I love to eat honey and berries, and I sleep all winter long.','I stand up on two legs and say GRRRR!']},
{e:'🐢', name:'a TURTLE!', clues:['I move v-e-r-y slowly and I am never in a hurry.','I carry my house on my back \u2014 it is a hard little shell!','When I feel shy I hide inside my shell. Peek-a-boo!']},
{e:'🐭', name:'a MOUSE!', clues:['I am teeny, teeny tiny and I love to hide.','I have two round ears, a long skinny tail, and I love cheese.','I scurry, scurry, scurry and say squeak-squeak!']},
{e:'🦀', name:'a CRAB!', clues:['I live at the beach, down in the sand and the waves.','I walk sideways instead of forwards \u2014 try it!','I pinch-pinch-pinch with my two big claws!']},
{e:'🐬', name:'a DOLPHIN!', clues:['I live in the ocean, but I am not a fish.','I am very, very smart and I love to leap out of the waves.','I splash and say eee-eee-eee!']},
  ]},

{ id:'name5', name:'Name 5', emoji:'🖐️', energy:'calm', hue:'#9B5DE5', kind:'std',
  how:'Read the category. They name 5 things that fit \u2014 hold up a finger for each one. Stuck at 3? Team up and finish together. High five when the hand is full!',
  cards:[
    {e:'🐾', k:'Name 5 ANIMALS!', p:'Any animals at all. Made-up sounds earn bonus points.'},
    {e:'🍎', k:'Name 5 FOODS!', p:'Then ask: which one should we eat after this?'},
    {e:'🍭', k:'Name 5 YUMMY TREATS!', p:'Prepare for a snack request. You brought this on yourself.'},
    {e:'🌊', k:'Name 5 things in the OCEAN!', p:'Fish, whales, mermaids \u2014 all accepted.'},
    {e:'🚜', k:'Name 5 things with WHEELS!', p:'Fingers up! Bikes, trucks, strollers\u2026'},
    {e:'🪽', k:'Name 5 things that FLY!', p:'Birds, planes, superheroes, balloons\u2026'},
    {e:'🐄', k:'Name 5 FARM animals!', p:'Make each one\u2019s sound as you count it.'},
    {e:'🧊', k:'Name 5 COLD things!', p:'Ice cream, snow, popsicles, penguins\u2026'},
    {e:'🔥', k:'Name 5 HOT things!', p:'Careful things! The sun, soup, lava\u2026'},
    {e:'🛏️', k:'Name 5 things in your BEDROOM!', p:'Can they picture their room from here?'},
    {e:'📣', k:'Name 5 things that make NOISE!', p:'Demonstrations encouraged, at whisper volume.'},
    {e:'🐋', k:'Name 5 things BIGGER than you!', p:'Then: 5 things smaller than your pinky.'},
    {e:'🦶', k:'Name 5 BODY PARTS!', p:'Touch each one as you name it. Littles: nose, tummy, toes is a full-celebration win.'},
    {e:'🧥', k:'Name 5 things you can WEAR!', p:'Pointing at what you\u2019re both wearing right now totally counts.'},
    {e:'🛝', k:'Name 5 things at the PLAYGROUND!', p:'Swing, slide, sandbox\u2026 then vote: which one first, next time?'},
    {e:'🎈', k:'Name 5 things at a BIRTHDAY PARTY!', p:'Cake, balloons, presents\u2026 stopping at 3 still earns the full hip-hip-hooray.'},
    {e:'🛁', k:'Name 5 things in the BATHTUB!', p:'Bubbles, a ducky, a boat\u2026 quiet splash sound effects encouraged.'},
    {e:'🍌', k:'Name 5 FRUITS!', p:'Repeats sneak in? Let them. Two fruits from a little one fills the whole hand.'},
    {e:'👀', k:'Name 5 things you can SEE right now!', p:'The easiest one on purpose \u2014 pointing counts, naming it is bonus. Perfect for the littlest players.'},
  ]},

{ id:'wyr', name:'Would You Rather', emoji:'🤔', energy:'calm', hue:'#F15BB5', kind:'choice',
  pDefault:'Read both choices out loud. Everyone picks \u2014 then ask the magic question: "WHY?" Silly answers only. There are no wrong answers.',
  how:'Read both options with maximum drama. Everyone answers \u2014 grown-ups too \u2014 and then everyone asks each other WHY. The why is where it gets good.',
  cards:[
    {a:['🐒','a monkey tail'], b:['🪽','bird wings']},
    {a:['🐭','be TINY as a mouse'], b:['🏔️','be HUGE as a giant']},
    {a:['🍦','eat only ice cream forever'], b:['🍕','eat only pizza forever']},
    {a:['🦖','a pet dinosaur'], b:['🐉','a pet dragon']},
    {a:['🌳','live in a treehouse'], b:['🏰','live in a castle']},
    {a:['🕊️','be able to FLY'], b:['👻','turn INVISIBLE']},
    {a:['🐾','talk to animals'], b:['🧸','talk to your toys']},
    {a:['🦘','bounce like a kangaroo'], b:['🐬','swim like a dolphin']},
    {a:['🍝','hair made of spaghetti'], b:['🌱','hair made of grass']},
    {a:['❄️','snow every day'], b:['☀️','sunshine every day']},
    {a:['🦄','ride a unicorn'], b:['🚀','ride a rocket']},
    {a:['✨','sneeze GLITTER'], b:['🫧','burp BUBBLES']},
    {a:['🦸','be a superhero'], b:['🧙','be a wizard']},
    {a:['🐶','have 100 puppies'], b:['🐱','have 100 kittens']},
    {a:['🧦','socks on your hands'], b:['🧤','mittens on your feet']},
    {a:['🐮','a cow that says QUACK'], b:['🦆','a duck that says MOO']},
    {a:['🥞','a pancake as big as the table'], b:['🧇','a waffle as big as your bed']},
    {a:['🍮','a bathtub full of jiggly jello'], b:['🏊','a pool full of marshmallows']},
    {a:['🐘','ride an elephant'], b:['🐋','ride a whale']},
    {a:['🎺','a nose that goes HONK'], b:['👟','shoes that go SQUEAK']},
    {a:['🐙','eight octopus arms'], b:['🦒','a looong giraffe neck']},
    {a:['☁️','bounce on the clouds'], b:['🌈','slide down a rainbow']},
    {a:['🍪','live in a cookie house'], b:['🛏️','live in a pillow fort']},
  ]},

{ id:'story', name:'Story Starters', emoji:'📖', energy:'calm', hue:'#5271FF', kind:'std',
  how:'Read the starter with your best storyteller voice, then take turns: one sentence each. When they pause, ask "and THEN what happened?!" The story ends whenever you reach the front of the line \u2014 or when everyone is giggling too hard.',
  cards:[
    {e:'🐉', k:'The Hungry Little Dragon', p:'Say: "Once upon a time, a tiny dragon was SO hungry\u2026 but the only thing left to eat was\u2026" \u2014 their turn!'},
    {e:'👟', k:'The Runaway Shoes', p:'Say: "One morning, all the shoes in the house ran away, because\u2026"'},
    {e:'🧑\u200d🚀', k:'The Little Astronaut', p:'Say: "A little astronaut landed on a planet made ENTIRELY of\u2026"'},
    {e:'👾', k:'The Friendly Monster', p:'Say: "The monster under the bed wasn\u2019t scary at all. It just really, really wanted\u2026"'},
    {e:'🦴', k:'The Magic Bone', p:'Say: "A puppy dug up a magic bone. Whoever held it could suddenly\u2026"'},
    {e:'🍦', k:'Ice Cream Truck on the Moon', p:'Say: "The ice cream truck got a flat tire\u2026 ON THE MOON! So\u2026"'},
    {e:'🚪', k:'The Door in the Tree', p:'Say: "Behind a tiny door in a big old tree, there was\u2026"'},
    {e:'🦸', k:'The Silliest Superhero', p:'Say: "The silliest superhero in the world had one power: they could\u2026"'},
    {e:'🌧️', k:'Raining Spaghetti', p:'Say: "One day it started to rain\u2026 SPAGHETTI! Everyone grabbed\u2026"'},
    {e:'🐭', k:'The Mouse Who Wanted to Be Big', p:'Say: "A tiny mouse wished to be as big as an elephant. So she\u2026"'},
    {e:'🍪', k:'The Cookies Come Alive', p:'Say: "At midnight, Grandma\u2019s cookies woke up and decided to\u2026"'},
    {e:'🐜', k:'Shrunk Down Small', p:'Say: "We shrank down as small as ants! Our shoe became our house, and\u2026"'},
    {e:'🐤', k:'The Little Duck\u2019s Big Splash', p:'Say: "A little duck jumped into a puddle \u2014 SPLASH! \u2014 and out of the puddle popped\u2026"'},
    {e:'🍌', k:'The Banana That Said Hello', p:'Say: "At breakfast, the banana wiggled, opened two tiny eyes, and said\u2026"'},
    {e:'🎈', k:'The Runaway Balloon', p:'Say: "A red balloon slipped away and floated up, up, UP \u2014 all the way to\u2026"'},
    {e:'🚌', k:'The Bus Full of Animals', p:'Say: "The bus doors opened and it was FULL of animals! And driving the bus was\u2026"'},
    {e:'🐋', k:'The Whale in the Bathtub', p:'Say: "We turned on the bath, and a whole WHALE popped up and said\u2026"'},
    {e:'🛏️', k:'The Flying Bed', p:'Say: "At bedtime, the bed went WHOOSH, flew right out the window, and landed\u2026"'},
    {e:'🧦', k:'The Sock Drawer Monster', p:'Say: "A teeny-tiny monster lived in the sock drawer, and every night it\u2026"'},
  ]},

{ id:'sounds', name:'Sound Detective', emoji:'👂', energy:'calm', hue:'#00B8A9', kind:'std',
  how:'Whisper: "Detective ears\u2026 ON!" Close your eyes (or just look down at your shoes) and listen hard for what\u2019s on the card. Great for calming a wound-up kiddo in a loud place.',
  cards:[
    {e:'📢', k:'Listen for something LOUD', p:'Point (eyes still closed!) toward where it came from.'},
    {e:'🤫', k:'Listen for the QUIETEST sound', p:'You have to get really still for this one. That\u2019s the point.'},
    {e:'🗣️', k:'Listen for a VOICE', p:'Can you hear what they\u2019re saying? Is it a kid or a grown-up?'},
    {e:'🎵', k:'Listen for MUSIC', p:'No music playing? Hum a tiny bit and see how fast they catch you.'},
    {e:'🛎️', k:'Listen for a BEEP or a DING', p:'Registers, phones, doors, trucks backing up.'},
    {e:'👣', k:'Listen for FOOTSTEPS', p:'Fast ones or slow ones? Big feet or little feet?'},
    {e:'🚗', k:'Listen for something with an ENGINE', p:'Car, truck, bus, plane \u2014 which one was it?'},
    {e:'🐦', k:'Listen for a BIRD', p:'Outside only \u2014 or is it? Some stores have sneaky sparrows.'},
    {e:'😄', k:'Listen for LAUGHING', p:'If you can\u2019t find any\u2026 make some.'},
    {e:'🔢', k:'Count the DIFFERENT sounds', p:'Eyes closed, ten seconds, fingers up for each new sound. Compare totals!'},
    {e:'🤖', k:'What\u2019s making the WEIRDEST sound?', p:'Find the strangest sound you can hear, then invent what\u2019s REALLY making it. A robot? A dragon snoring?'},
    {e:'🍽️', k:'Listen for CLINKS and CLANKS', p:'Forks on plates, glasses, a spoon stirring \u2014 the dinner-table song.'},
    {e:'💧', k:'Listen for WATER', p:'Pouring, a splash, ice cubes, a faraway sink. Trickle, trickle.'},
    {e:'🚪', k:'Listen for a DOOR', p:'Opening, closing, a little bell when someone walks in.'},
    {e:'🥤', k:'Listen for a SLURP or a CRUNCH', p:'A straw, crunchy chips, someone taking a sip. You can make one too.'},
    {e:'🍳', k:'Listen for SIZZLING from the kitchen', p:'That hiss when food is cooking. Sniff, too \u2014 can you smell it?'},
    {e:'📍', k:'Which sound is CLOSE and which is FAR?', p:'Pick two sounds. Point at the near one, then way off at the far one.'},
  ]},

{ id:'rhyme', name:'Rhyme Time', emoji:'🎤', energy:'calm', hue:'#D96BFF', kind:'std',
  how:'Say the word on the card. Take turns saying words that rhyme with it \u2014 real words OR silly made-up ones. Can\u2019t think of one? Say it in a robot voice and try again. Keep going until you both run dry, then flip the card.',
  cards:[
    {e:'🐱', k:'CAT', p:'Hat, bat, mat, sat, rat\u2026 splat!'},
    {e:'🐶', k:'DOG', p:'Frog, log, jog, fog\u2026 bog!'},
    {e:'🐝', k:'BEE', p:'Tree, see, me, key, three!'},
    {e:'⭐', k:'STAR', p:'Car, far, jar\u2026 are!'},
    {e:'🎂', k:'CAKE', p:'Lake, snake, shake, rake\u2026 mistake!'},
    {e:'⚽', k:'BALL', p:'Tall, small, wall, fall, hall!'},
    {e:'🐭', k:'MOUSE', p:'House, blouse\u2026 this one runs out fast, so silly words save the day.'},
    {e:'🐛', k:'BUG', p:'Hug, rug, mug, tug\u2026 glug!'},
    {e:'🌙', k:'MOON', p:'Spoon, soon, noon, balloon!'},
    {e:'🧦', k:'SOCK', p:'Rock, block, clock, knock-knock!'},
    {e:'🚂', k:'TRAIN', p:'Rain, brain, chain, plane!'},
    {e:'🐷', k:'PIG', p:'Big, dig, wig, fig\u2026 jig! (Do the jig.)'},
    {e:'☀️', k:'SUN', p:'Fun, run, bun, one\u2026 zun!'},
    {e:'🛏️', k:'BED', p:'Red, head, bread, sled\u2026 zed!'},
    {e:'🍿', k:'POP', p:'Hop, top, stop, mop\u2026 boppity-bop!'},
    {e:'🚐', k:'VAN', p:'Man, can, fan, pan\u2026 flan!'},
    {e:'🐔', k:'HEN', p:'Ten, pen, men, when\u2026 again! (Again? Again.)'},
    {e:'👑', k:'KING', p:'Ring, sing, wing, swing\u2026 bling!'},
    {e:'⛵', k:'BOAT', p:'Goat, coat, note, float\u2026 moat!'},
  ]},

{ id:'simon', name:'Simon Says', emoji:'🫡', energy:'active', hue:'#FF6B6B', kind:'std',
  how:'You\u2019re Simon! Read each card out loud EXACTLY as written. If it starts with "Simon says," they do it. If it doesn\u2019t \u2014 they should freeze! Got tricked? Giggle and keep playing. With very little ones, skip the tricks and just do the moves together.',
  cards:[
    {e:'👃', k:'Touch your nose', p:'Say: "Simon says\u2026 touch your nose!"'},
    {e:'🦶', k:'Touch your toes', p:'Say: "Simon says\u2026 touch your toes!"'},
    {e:'🙌', k:'Hands on your head', p:'Say: "Simon says\u2026 put your hands on your head!"', trick:false},
    {e:'🐇', k:'Hop 3 times', p:'Say: "Simon says\u2026 hop three times!" Tiny hops \u2014 we\u2019re in a line.'},
    {e:'🪼', k:'Wiggle like jelly', p:'Say: "Simon says\u2026 wiggle like jelly!"'},
    {e:'🗿', k:'Freeze like a statue', p:'Say: "Simon says\u2026 freeze like a statue!" See how long they last.'},
    {e:'👀', k:'Blink super fast', p:'Say: "Simon says\u2026 blink as fast as you can!"'},
    {e:'😝', k:'Stick out your tongue', p:'TRICK! Say just: "Stick out your tongue!" \u2014 did they freeze, or are you looking at a tongue?', trick:true},
    {e:'🙆', k:'Arms up high', p:'Say: "Simon says\u2026 reach up as high as you can!"'},
    {e:'👏', k:'Three tiny claps', p:'Say: "Simon says\u2026 do three tiny quiet claps!"'},
    {e:'🥾', k:'Stomp softly', p:'TRICK! Say just: "Stomp your feet!" \u2014 freeze check!', trick:true},
    {e:'🔄', k:'Turn around once', p:'Say: "Simon says\u2026 turn around one time!"'},
    {e:'🤪', k:'Make a silly face', p:'Say: "Simon says\u2026 make your silliest face!" You have to make one back.'},
    {e:'🐔', k:'Flap like a chicken', p:'TRICK! Say just: "Flap your wings!" \u2014 anyone flapping is a chicken.', trick:true},
    {e:'👍', k:'Thumbs up', p:'Say: "Simon says\u2026 give me a thumbs up!"'},
    {e:'🤫', k:'Whisper your name', p:'Say: "Simon says\u2026 whisper your name as quietly as you can."'},
    {e:'😁', k:'Biggest smile', p:'TRICK! Say just: "Smile really big!" \u2014 nobody can resist this one. Gotcha.', trick:true},
    {e:'👂', k:'Touch your ears', p:'Say: "Simon says\u2026 touch your ears!"'},
    {e:'🦩', k:'Stand on one foot', p:'Say: "Simon says\u2026 stand on one foot like a flamingo!"'},
    {e:'🫲', k:'Shake my hand', p:'TRICK! Say just: "Shake my hand!" while offering it. Diabolical. Shake anyway if they fall for it.', trick:true},
    {e:'👐', k:'Wiggle all ten fingers', p:'Say: "Simon says\u2026 wiggle all ten fingers like tiny wiggly worms!"'},
    {e:'🤷', k:'Shrug up to your ears', p:'Say: "Simon says\u2026 scrunch your shoulders WAY up to your ears\u2026 now let them flop down!"'},
    {e:'🎈', k:'Puff up your cheeks', p:'Say: "Simon says\u2026 puff your cheeks up like a big balloon!" Pop it with a gentle poke.'},
    {e:'🤗', k:'Give yourself a hug', p:'Say: "Simon says\u2026 wrap your arms around and give yourself the biggest squeezy hug!"'},
    {e:'🙈', k:'Cover your eyes', p:'Say: "Simon says\u2026 cover your eyes with both hands\u2026 peekaboo!"'},
    {e:'🤐', k:'Zip your lips', p:'Say: "Simon says\u2026 zip your lips and throw away the key!" Enjoy the quiet while it lasts.'},
    {e:'👆', k:'Point at the ceiling', p:'Say: "Simon says\u2026 point one finger way up at the ceiling!"'},
    {e:'🙋', k:'Wave hello', p:'TRICK! Say just: "Wave hello!" \u2014 anyone waving got got.', trick:true},
    {e:'💋', k:'Blow a kiss', p:'TRICK! Say just: "Blow me a kiss!" \u2014 freeze check! (Blow one right back if they melt you.)', trick:true},
  ]},

{ id:'freeze', name:'Freeze!', emoji:'🧊', energy:'active', hue:'#4CC9F0', kind:'std',
  how:'Say "WIGGLE WIGGLE WIGGLE!" \u2014 everyone wiggle-dances in place. Then call "FREEZE!" and show the card: hold that pose while you count to five. Wobbling means giggling means go again. Pretending to BE the thing helps them hold still way longer.',
  cards:[
    {e:'⭐', k:'Freeze like a STAR', p:'Arms and legs out wide. Count to 5 \u2014 slower each round.'},
    {e:'🦩', k:'Freeze like a FLAMINGO', p:'One foot up! Grab a shoulder if the floor is lava-wobbly.'},
    {e:'🦸', k:'Freeze like a SUPERHERO', p:'Fists on hips, chin up, cape imaginary.'},
    {e:'🤖', k:'Freeze like a ROBOT', p:'Stiff arms, square angles. Powering down\u2026 beep\u2026 boop\u2026'},
    {e:'😴', k:'Freeze like a SLEEPING CAT', p:'Standing up! Paw-hands, eyes closed, one tiny fake snore allowed.'},
    {e:'🩰', k:'Freeze like a BALLERINA', p:'Up on tippy-toes, arms in a circle. Hardest one!'},
    {e:'🦍', k:'Freeze like a GORILLA', p:'Big arms, knuckles low, mid chest-thump. Silent roar face.'},
    {e:'🌳', k:'Freeze like a TREE', p:'Arms are branches. A gentle breeze may sway you\u2026 but just barely.'},
    {e:'🍝', k:'Freeze like SPAGHETTI', p:'First wiggle like cooked spaghetti\u2026 then FREEZE stiff like uncooked spaghetti!'},
    {e:'🏄', k:'Freeze like a SURFER', p:'Knees bent, arms out, riding an invisible wave.'},
    {e:'💪', k:'Freeze like a STRONG-PERSON', p:'Double arm flex. Grrr face required.'},
    {e:'🐭', k:'Freeze like a TINY MOUSE', p:'Crouch small-small-small. Whisker hands. Squeak once, then silence.'},
    {e:'🐢', k:'Freeze like a SCARED TURTLE', p:'Pull your head down into your shell \u2014 chin to chest, shoulders up, arms tucked tight. Nobody home!'},
    {e:'🦁', k:'Freeze like a PROUD LION', p:'Sit up tall, chest puffed out, big mane-hands framing your face. One silent, mighty roar.'},
    {e:'🪆', k:'Freeze like a RAG DOLL', p:'Go all floppy \u2014 head tipped over, arms dangling like cooked noodles. Frozen, but wobbly-soft.'},
    {e:'🚀', k:'Freeze like a ROCKET', p:'Arms shoot straight up over your head into a pointy tip. Countdown to blast-off\u2026 and HOLD!'},
    {e:'🦖', k:'Freeze like a T-REX', p:'Tiny arms tucked to your chest, jaw open mid-roar, eyes wide. Frozen at the scariest part.'},
    {e:'😎', k:'Freeze like a COOL CUCUMBER', p:'Arms crossed, chin up, invisible sunglasses on. Waaay too cool to move a single muscle.'},
    {e:'🦉', k:'Freeze like an OWL', p:'Huge round eyes, wing-arms folded in, head perfectly still on your branch. Whooo can hold it longest?'},
  ]},

{ id:'walks', name:'Silly Walks', emoji:'🐧', energy:'active', hue:'#7BC950', kind:'std',
  how:'This one is FOR when the line moves! Each time you shuffle forward, walk to the next spot the way the card says. When the line stops \u2014 freeze in character until it moves again. The waiting becomes the game.',
  cards:[
    {e:'🤖', k:'Walk like a ROBOT', p:'Stiff legs, stiff arms. Beep with each step.'},
    {e:'🥷', k:'Sneak like a NINJA', p:'Silent tippy-toes. If anyone hears you, you must start again.'},
    {e:'🐧', k:'Waddle like a PENGUIN', p:'Feet together, arms flat at your sides, waddle-waddle.'},
    {e:'🦣', k:'Stomp like a GIANT', p:'Giant SLOW steps \u2014 soft stomps, we\u2019re being polite giants.'},
    {e:'🐭', k:'Scurry like a MOUSE', p:'Teeny-tiny fast steps. How many tiny steps to the next spot?'},
    {e:'🥁', k:'March like a DRUMMER', p:'Knees up! Pat the drum-beat on your legs as you march.'},
    {e:'🧑\u200d🚀', k:'Moon-walk like an ASTRONAUT', p:'Slooow bouncy steps. There\u2019s no gravity in this line.'},
    {e:'🦀', k:'Scuttle like a CRAB', p:'Side-steps only! Pinchy claw hands.'},
    {e:'🦥', k:'Creep like a SLOTH', p:'The sloooowest walk ever. Perfect for a slow line.'},
    {e:'🐰', k:'Hop like a BUNNY', p:'Little hops, paws up. Nose wiggles at each stop.'},
    {e:'👑', k:'Strut like ROYALTY', p:'Nose in the air, tiny fancy steps, royal wave at your subjects.'},
    {e:'🧟', k:'Shuffle like a ZOMBIE', p:'Arms out, dragging feet, quiet "braaains\u2026" (or "snaaacks\u2026").'},
    {e:'🦖', k:'Stomp like a T-REX', p:'Tiny arms tucked in, big soft stomps, one small roar.'},
    {e:'🎪', k:'Walk the TIGHTROPE', p:'Heel-to-toe on an imaginary rope. Arms out for balance \u2014 don\u2019t fall in the crocodile pit!'},
    {e:'🐴', k:'Trot like a PONY', p:'Knees high, tiny clip-clop steps, toss your mane at each stop. Quiet tongue-click hooves if you\u2019ve got them.'},
    {e:'🐘', k:'Sway like an ELEPHANT', p:'One arm is your trunk \u2014 swing it looow and slow with each big step. One tiny trumpet when you arrive.'},
    {e:'🥜', k:'Walk through PEANUT BUTTER', p:'The floor is sticky-sticky! Peel each foot up sloooowly with your best squelchy face. Hardest three steps of your life.'},
    {e:'🚂', k:'Chug like a TRAIN', p:'Arms are wheels, chugga-chugga quietly. Whoever\u2019s in front is the engine, everyone else is cars. Whisper the whistle: "woo-woooo\u2026"'},
    {e:'🤠', k:'Mosey like a COWBOY', p:'Bow legs, thumbs in your belt, the slooowest mosey in the West. Tip your invisible hat: "howdy, partner."'},
  ]},

{ id:'copycat', name:'Copycat', emoji:'🪞', energy:'active', hue:'#FF8FA3', kind:'std',
  how:'Do what the card says \u2014 kiddo copies you exactly. Then SWAP: they invent, you copy (mess it up a little; being copied badly is hilarious). Add speed for extra giggles.',
  cards:[
    {e:'👏', k:'Copy the CLAPS', p:'Clap a pattern: clap-clap-STOMP. They echo it. Make it one beat longer each round.'},
    {e:'🪞', k:'Slow-motion MIRROR', p:'Face each other. Move super slowly \u2014 they mirror you like a reflection. Then swap leaders.'},
    {e:'🤪', k:'Funny face contest', p:'Make a face, they copy it. Take turns. No laughing\u2026 impossible.'},
    {e:'🤯', k:'Pat head, rub tummy', p:'Both at once! Then swap hands. Then\u2026 while balancing on one foot?'},
    {e:'⚡', k:'Head-shoulders-knees-toes', p:'Once slow, once medium, once LUDICROUS SPEED.'},
    {e:'😉', k:'Wink practice', p:'Wink one eye, then the other. Little kids\u2019 double-blink attempts are the best thing you\u2019ll see all day.'},
    {e:'🥁', k:'Air drums', p:'Play an invisible drum solo. They copy your solo, then perform their own. Nod respectfully.'},
    {e:'🤨', k:'Eyebrow wiggles', p:'Wiggle your eyebrows. Can they do one at a time? Can YOU?'},
    {e:'🖐️', k:'Slow-motion high five', p:'The slowest high five in history. Dramatic wind-up. Gentle landing. "Niiiiice."'},
    {e:'🎾', k:'Sound Ball', p:'Pretend-throw a ball while making a silly sound \u2014 "BOING!" They catch it making the SAME sound, then throw it back with a NEW sound.'},
    {e:'🧺', k:'The Picnic Game', p:'Say: "I\u2019m going on a picnic and bringing\u2026 apples." They repeat the list and add one thing. How long can the list get?'},
    {e:'🕺', k:'Copy the dance move', p:'One move at a time: spin, wiggle, point. String them into a tiny line-dance routine.'},
    {e:'🐰', k:'Animal hands', p:'Make bunny ears\u2026 a creeping snail\u2026 a flapping bird\u2026 a snapping crocodile. They copy each one. Then they invent an animal and YOU guess it.'},
    {e:'🎩', k:'Invisible dress-up', p:'Mime putting on a hat \u2014 they copy. Add glasses\u2026 a mustache\u2026 a superhero cape\u2026 Then admire each other: "Ooh, FANCY."'},
    {e:'🥱', k:'The contagious yawn', p:'Do your biggest, slowest fake yawn. Did they catch it? Yawns really are contagious \u2014 you\u2019re basically doing science.'},
    {e:'🐡', k:'Puffer fish cheeks', p:'Puff your cheeks up big-big-big. They copy. Gently poke theirs \u2014 pfffft! Then it\u2019s their turn to poke yours.'},
    {e:'👂', k:'Nose and ear switcheroo', p:'Left hand on your nose, right hand on your ear. Now SWITCH! Slow at first\u2026 then speedy. Everyone tangles up. That\u2019s the game.'},
    {e:'✏️', k:'Air drawing', p:'Draw a big shape in the air with one finger \u2014 they trace the same one. Circle, star, zigzag\u2026 then a letter from their name!'},
    {e:'🤫', k:'Whisper echo', p:'Whisper a silly word in a funny voice \u2014 "noooooodles\u2026" They echo it exactly. Squeaky, growly, wobbly. The quietest game in the book.'},
  ]},

{ id:'hands', name:'Hand Games', emoji:'✋', energy:'active', hue:'#FFB627', kind:'std',
  how:'Every card is a tiny hand game \u2014 perfect for staying put. Read the card and play right there. Hands only, feet optional, giggles guaranteed.',
  cards:[
    {e:'✊', k:'Rock, Paper, Scissors', p:'"Rock, paper, scissors\u2026 SHOOT!" ✊ crushes ✌️, ✌️ cuts ✋, ✋ wraps ✊. Best of three. Littles can just copy your hand \u2014 that\u2019s a win too.'},
    {e:'👍', k:'Thumb War', p:'Hook fingers: "1, 2, 3, 4 \u2014 I declare a thumb war!" Pin their thumb for a count of 3. Lose dramatically.'},
    {e:'🖐️', k:'Hand Stack', p:'Stack all your hands in a tower. Bottom hand flies to the top. Faster\u2026 faster\u2026 until it collapses!'},
    {e:'🤝', k:'Invent a Secret Handshake', p:'Take turns adding ONE move at a time: fist bump\u2026 then wiggle\u2026 then elbow tap\u2026 How many moves can you both remember?'},
    {e:'🖐', k:'Up High, Down Low', p:'"Up high! Down low!\u2026 TOO SLOW!" Then let them get you back. Always let them get you back.'},
    {e:'👏', k:'Echo Claps', p:'Clap a rhythm \u2014 they clap it back like an echo. Start with 2 claps, build up. Then they lead.'},
    {e:'🔢', k:'Finger Flash', p:'"Show me 3 fingers! Now 5! Now 1! Now 4!" Faster and faster. Then swap: they call, you flash (get one wrong on purpose).'},
    {e:'🫸', k:'Sticky Hands', p:'Press your palms together with theirs. "Oh no\u2026 they\u2019re STUCK! 1\u2026 2\u2026 3\u2026 UNSTICK!" Fling apart dramatically.'},
    {e:'🕷️', k:'Itsy Bitsy Spider', p:'The classic finger play: spider climbs up, rain washes it out, sun comes up, spider climbs again. Perfect for the littlest waiters.'},
    {e:'🧸', k:'Round and Round the Garden', p:'Trace a slow circle on their palm: "Round and round the garden, like a teddy bear\u2026 one step, two step\u2026 TICKLE under there!"'},
    {e:'🧁', k:'Pat-a-Cake', p:'The original: "Pat-a-cake, pat-a-cake, baker\u2019s man\u2026" Roll it, pat it, mark it with their letter \u2014 then shove the pretend pan into the oven together.'},
    {e:'🐦', k:'Two Little Birds', p:'Two finger-birds sit on the table: "Fly away, Peter! Fly away, Paul!" \u2014 hide them behind your back \u2014 "Come back, Peter! Come back, Paul!" Littles are mystified every single time.'},
    {e:'👐', k:'Open, Shut Them', p:'"Open, shut them, open, shut them, give a little clap!" Then creep your fingers up to their chin\u2026 "but do NOT let them in!" Ends with hands quietly in laps. Sneaky calm-down.'},
    {e:'🐊', k:'Crocodile Snap', p:'Your open hand is a sleeping crocodile. They sneak one finger in to poke your palm\u2026 SNAP! Too slow, croc. Then their croc, your finger.'},
    {e:'🤜', k:'Guess Which Hand', p:'Hide something tiny \u2014 a sugar packet, a coin \u2014 behind your back, then fists out. They tap one. Wrong? Gasp, try again. Then they hide it: act amazed no matter how much is sticking out of their fist.'},
    {e:'🤲', k:'Squeeze Code', p:'Hold hands under the table. One squeeze means hello, two means make a silly face, three means I love you. Send secret messages nobody else can see.'},
    {e:'🐟', k:'Once I Caught a Fish Alive', p:'"1, 2, 3, 4, 5 \u2014 once I caught a fish alive! 6, 7, 8, 9, 10 \u2014 then I let it go again." Which finger did it bite? "This little finger on the right!" Wiggle it. Ouch.'},
  ]},

{ id:'feelings', name:'Feelings Faces', emoji:'😊', energy:'calm', hue:'#FF9770', kind:'std',
  how:'Read the feeling out loud, then make that face together \u2014 the sillier the better. Ask "what makes YOU feel this way?" for bonus giggles and a peek into their day.',
  cards:[
    {e:'😄', k:'Show me your HAPPY face!', p:'Big smile, bright eyes, maybe a little wiggle. What made you happy today?'},
    {e:'😢', k:'Show me your SAD face!', p:'Droopy mouth, droopy eyes. It\u2019s okay to feel sad \u2014 what makes YOU feel this way?'},
    {e:'😠', k:'Show me your MAD face!', p:'Scrunched-up eyebrows, puffy cheeks. Growl your maddest grrr\u2026 then let it all go \u2014 pfffft.'},
    {e:'😨', k:'Show me your SCARED face!', p:'Wide eyes, open mouth, hands up by your cheeks. What\u2019s something that feels a little scary?'},
    {e:'😲', k:'Show me your SURPRISED face!', p:'Eyebrows UP, mouth a big round O \u2014 gasp! Like someone yelled "surprise!"'},
    {e:'🥱', k:'Show me your SLEEPY face!', p:'Great big yawn, heavy eyes, a sloooow stretch. Try not to yawn for real\u2026 too late?'},
    {e:'🤪', k:'Show me your SILLIEST face!', p:'Tongue out, crossed eyes, whatever\u2019s goofiest. Now make one even sillier!'},
    {e:'😌', k:'Show me your PROUD face!', p:'Sit up tall, chest out, big grin \u2014 "I did it!" What\u2019s something you did all by yourself?'},
    {e:'🙈', k:'Show me your SHY face!', p:'Peek out from behind your hands with a little smile. New things can feel shy, and that\u2019s okay.'},
    {e:'🤩', k:'Show me your EXCITED face!', p:'Sparkly eyes, huge smile, happy wiggles! What are you excited about?'},
    {e:'😒', k:'Show me your GRUMPY face!', p:'Arms crossed, bottom lip out, little frown. Everybody feels grumpy sometimes \u2014 even grown-ups.'},
    {e:'🦁', k:'Show me your BRAVE face!', p:'Chin up, strong eyes, one tiny brave roar. Brave means trying even when it feels a little scary.'},
    {e:'🤔', k:'Show me your CONFUSED face!', p:'One eyebrow up, head tilted \u2014 "hmmmm?" It\u2019s okay not to know. We can figure it out together.'},
    {e:'🤢', k:'Show me your YUCKY face!', p:'Scrunch your nose, stick out your tongue \u2014 bleh! What food gives you this face?'},
    {e:'🧐', k:'Show me your CURIOUS face!', p:'Lean in with big wondering eyes \u2014 "ooh, what\u2019s THAT?" What do you want to know more about?'},
    {e:'🧘', k:'Show me your CALM face!', p:'Soft eyes, easy smile. Take one big slow breath in\u2026 and let it out. Ahhh.'},
    {e:'🥰', k:'Show me your LOVING face!', p:'Warm smile, squishy cheeks, maybe a little self-hug. Who do you love the most?'},
  ]},

{ id:'opposites', name:'Opposites', emoji:'⚖️', energy:'calm', hue:'#118AB2', kind:'std',
  how:'Read the question, point together, then say the answer out loud \u2014 no wrong guesses here. Bonus: act it out! Big means big arms, tiny means a teeny scrunch.',
  cards:[
    {e:'🐘🐭', k:'Which is BIGGER: an elephant or a mouse?', p:'Act it out \u2014 stomp-big arms for elephant, squeaky-tiny pinch for mouse. Then: what\u2019s even bigger than an elephant?'},
    {e:'🚒🦋', k:'Which is LOUDER: a fire truck or a butterfly?', p:'Do a whisper-quiet siren together. Butterfly wings make almost no sound at all \u2014 that\u2019s as quiet as it gets.'},
    {e:'🐆🐌', k:'Which is FASTER: a cheetah or a snail?', p:'Cheetahs are the fastest runners on Earth! Race your fingers across the table: one ZOOMS, one slooooowly slides.'},
    {e:'☀️🧊', k:'Which is HOTTER: the sun or an ice cube?', p:'Then scan the table: what\u2019s the hottest thing here? The coldest? Hover-hands only near the hot stuff.'},
    {e:'🚌🪶', k:'Which is HEAVIER: a school bus or a feather?', p:'Try to lift the invisible bus \u2014 hnnnngh! Then let the invisible feather float down onto your nose.'},
    {e:'🐟🐱', k:'Which is WETTER: a fish or a kitty cat?', p:'Fish are wet their whole lives! Most cats HATE getting wet. Make a soggy-cat face together.'},
    {e:'👵👶', k:'Who is OLDER: a grandma or a baby?', p:'Follow-up: who\u2019s the oldest person THEY know? Brace yourself \u2014 it might be you.'},
    {e:'🦒🐶', k:'Which is TALLER: a giraffe or a puppy?', p:'Stretch your neck up looong like a giraffe \u2014 it could peek into an upstairs window! A puppy checks under the table.'},
    {e:'🪨🧸', k:'Which is HARDER: a rock or a teddy bear?', p:'Test it live: knock-knock on the table (hard!), squish a sleeve (soft!). Find one more of each within reach.'},
    {e:'👃🌙', k:'Which is CLOSER: your nose or the moon?', p:'Boop the nose \u2014 SO close. Point at the moon \u2014 so far you can\u2019t touch it even on tippy-toes. Try anyway.'},
    {e:'🌞⭐', k:'Who comes out at NIGHT: the sun or the stars?', p:'Twinkle your fingers like tiny stars. Follow-up: what do YOU come out at night to do? (Trick question \u2014 you\u2019re supposed to be asleep!)'},
    {e:'🛁🥄', k:'Which holds MORE: a bathtub or a spoon?', p:'Then check the table: whose cup is the fullest right now? Take a sip\u2026 NOW whose is the emptiest?'},
    {e:'🚂🚗', k:'Which is LONGER: a train or a car?', p:'Stretch your arms as wiiiide as they go for the train. A car fits in one little clap. Chugga-chugga, quietly.'},
    {e:'✈️🐝', k:'Which flies HIGHER: an airplane or a bee?', p:'One hand soars way up high, the other buzzes low over the table. Planes fly higher than the clouds!'},
    {e:'🍋🍭', k:'Which is more SOUR: a lemon or a lollipop?', p:'Make the lemon face \u2014 pucker up! Then the lollipop face \u2014 mmmmm. Now switch faces faster and faster.'},
    {e:'🐷🫧', k:'Which is DIRTIER: a pig in the mud or a kid in the bath?', p:'Pigs roll in mud to keep cool \u2014 it\u2019s their sunscreen! Follow-up: what\u2019s the muddiest THEY\u2019ve ever been?'},
    {e:'🐊🥚', k:'Which is BUMPIER: a crocodile or an egg?', p:'Croc backs wear bumpy armor; eggs are smooth as can be. Find one bumpy thing and one smooth thing without leaving your seat.'},
  ]},

{ id:'missing', name:'What\u2019s Missing?', emoji:'🔍', energy:'calm', hue:'#E76F51', kind:'std',
  how:'Line up a few small things on the table \u2014 a couple of forks, a sugar packet, a coaster. Let them stare hard and really memorize the lineup, then cover it all with a napkin (or your two hands). Sneak ONE thing away, whisk the napkin off, and gasp: "What\u2019s MISSING?!" Start with just 2 things for the littlest detectives \u2014 an easy, guaranteed win \u2014 then build up to 4, 5, or 6 as they get sharper. No table stuff handy? Use fingers, or things you both just picture in your heads. Then swap: they hide, you guess (get it wrong once \u2014 it\u2019s funnier that way).',
  cards:[
    {e:'🥄', k:'Just Two to Start', p:'The 3-year-old special: line up ONLY a spoon and a fork. Stare hard, cover with a napkin, sneak one into your lap. "Spoon or fork \u2014 which one ran away?" An easy first win before you make it trickier.'},
    {e:'🍴', k:'The Whole Utensil Crew', p:'Fork, knife, spoon in a row \u2014 add a teaspoon or a chopstick for 4-6 pieces once they\u2019re warmed up. Napkin over the top, whisk one away. Big kids can close their eyes for extra fairness.'},
    {e:'🧂', k:'Salt, Pepper, and Pals', p:'Line up the salt, the pepper, a little jam tub, a creamer cup. Cover with the napkin, pocket one. Sneaky twist: bring it back tipped on its side \u2014 does a knocked-over one still count as here?'},
    {e:'🍬', k:'The Sweetener Rainbow', p:'Fan out the sugar packets \u2014 white, pink, blue, yellow. Cover, slide one out. They call the missing one by its COLOR, so no reading needed. Four colors is a perfect medium challenge.'},
    {e:'🥤', k:'Two Straws, No Mercy', p:'Easiest tier: just two straws (or a straw and its paper wrapper). Cover with your cupped hand, palm one away. About as toddler-proof as a win gets.'},
    {e:'🟫', k:'Coasters and Coffee-Stuff', p:'Stack of coasters, a stir stick, a creamer, a sugar packet \u2014 four things in a row. Napkin down, one gone. For older kids, run six and watch them squint.'},
    {e:'👟', k:'What Are You Wearing?', p:'Point to 3 things they\u2019ve got on \u2014 a shoe, a sock, a hair clip. "Eyes shut!" Whisk ONE clean off (yes, actually take the shoe). Eyes open: what did the grown-up steal?'},
    {e:'🧦', k:'Just Two Feet', p:'Easiest body version: both their shoes on and wiggling. "Close your eyes!" Slip ONE shoe off under the table. Which foot went bare? A giggly, guaranteed win for a 3-year-old.'},
    {e:'💍', k:'Whose Hands Are These?', p:'Look hard at what\u2019s on their hands \u2014 a bracelet, a sticker, a pretend ring made from a straw wrapper. Cover them with your hands, then sneak ONE thing off. What\u2019s gone from the collection?'},
    {e:'🐘', k:'The Zoo in Your Head', p:'No props needed. Say three animals slowly \u2014 "elephant\u2026 duck\u2026 snake" \u2014 and have them picture each one. Then list only TWO. Which animal tiptoed out of their imagination?'},
    {e:'🗣️', k:'Two Little Words', p:'Nothing on the table? Say two words \u2014 "banana, sock." They say them right back. Then whisper just ONE. Which word floated away? Bump up to three or four words as they get sharp.'},
    {e:'✋', k:'The Disappearing Finger', p:'Hold up 5 fingers and count them together, touching each one. "Eyes closed!" Fold one down. Open: how many now \u2014 and WHICH finger is hiding? Pure counting magic, zero props.'},
    {e:'✨', k:'What\u2019s NEW?', p:'Flip the game: line up 3 things, cover them, then ADD one more instead of taking any away. Whisk the napkin \u2014 something extra appeared! Sneaking a ketchup packet into the crew never gets old.'},
    {e:'🔄', k:'What MOVED?', p:'No hiding at all: line up 3 or 4 things, cover, then swap two of them so they trade places. Reveal: everything\u2019s still here \u2014 but what shuffled around? The trickiest one \u2014 save it for last.'},
  ]},

{ id:'datenight', name:'Date Night', emoji:'🥂', energy:'calm', hue:'#FF5D8F', kind:'std', plabel:'FOR YOU TWO',
  pDefault:'You both have to pick \u2014 no \u201cboth!\u201d allowed. Then say why.',
  how:'Read the card out loud. One of you answers first \u2014 then the other (no \u201csame!\u201d allowed, give your own answer). Follow-up questions are encouraged, phones are not.',
  cards:[
    {e:'🍕', k:'What\u2019s the food you could eat every day for a year?', p:'Follow-up: which food should be banned from this table forever?'},
    {e:'🦸', k:'What\u2019s your most useless talent?', p:'Demonstrations at the table are encouraged (within reason).'},
    {e:'🎤', k:'What song do you secretly know every word to?', p:'Bonus: hum four seconds of it right now.'},
    {e:'🛒', k:'What\u2019s the weirdest thing you\u2019ve ever bought at 11pm?', p:'Online shopping confessions count double.'},
    {e:'🐙', k:'If you were an animal, which one \u2014 and which one am I?', p:'You have to explain your reasoning. Flattery optional.'},
    {kind:'choice', a:['🏔️','A cabin in the mountains'], b:['🏖️','A bungalow on the beach']},
    {e:'🕵️', k:'What\u2019s a hill you will absolutely die on?', p:'The pettier, the better. Defend it like a lawyer.'},
    {e:'👻', k:'What\u2019s your most irrational fear?', p:'Follow-up: has it ever actually happened?'},
    {e:'🍿', k:'What movie can you quote way too much of?', p:'Do the quote. Commit to the voice.'},
    {e:'🧦', k:'What\u2019s the most \u2018you\u2019 thing you did this week?', p:'The other person gets to confirm or overrule.'},
    {e:'🛸', k:'You get one totally impractical superpower. What is it?', p:'No flying, no invisibility \u2014 pick something weird.'},
    {kind:'choice', a:['🌅','Be effortlessly early-morning people'], b:['🌃','Be guilt-free night owls']},
    {e:'😏', k:'What was your first impression of me?', p:'Be honest. Then say what changed \u2014 or what turned out true.'},
    {e:'💘', k:'When did you first realize you liked me?', p:'The exact moment, if you can. Details required.'},
    {e:'🔥', k:'What do I do that you find weirdly attractive?', p:'The weirder and more specific, the better.'},
    {e:'💃', k:'Describe our first date from your side of the table.', p:'New couple? Describe THIS date so far instead.'},
    {e:'😉', k:'What\u2019s your favorite compliment you\u2019ve ever received?', p:'Now give the other person one just as good.'},
    {kind:'choice', a:['🍳','A fancy dinner out every Friday'], b:['👨‍🍳','Cooking something new together every Friday']},
    {e:'💋', k:'What\u2019s your idea of a perfect kiss moment?', p:'Rain? Doorstep? Middle of a sentence? Take notes.'},
    {e:'🎯', k:'What little thing do I do that always makes you smile?', p:'Bonus points if I didn\u2019t know I was doing it.'},
    {e:'🕺', k:'If we had a couple\u2019s theme song, what would it be?', p:'You each pick one, then negotiate. This is binding.'},
    {e:'🌹', k:'What\u2019s the most romantic thing anyone\u2019s ever done for you?', p:'The bar is now set. No pressure.'},
    {e:'📸', k:'What\u2019s a moment with me you wish you had on video?', p:'Reenactments welcome.'},
    {kind:'choice', a:['🔁','Relive our best day together once a year'], b:['✨','Guaranteed one brand-new great day each year']},
    {e:'😂', k:'What\u2019s the hardest we\u2019ve ever laughed together?', p:'Warning: retelling it may cause a repeat incident.'},
    {e:'🗺️', k:'What\u2019s your favorite place we\u2019ve been together?', p:'Could be Paris. Could be a parking lot at 2am.'},
    {e:'🎁', k:'What\u2019s the best gift you\u2019ve ever gotten from anyone?', p:'Follow-up: what made it perfect \u2014 the thing, or the person?'},
    {e:'🍝', k:'What\u2019s our most \u2018us\u2019 meal \u2014 the one that tastes like this relationship?', p:'New couple? What meal do you predict will become \u2018yours\u2019?'},
    {e:'⏪', k:'If you could relive one day of your life, which one?', p:'Relive as-is \u2014 no changing anything. Just enjoying it again.'},
    {kind:'choice', a:['🎬','Star in a rom-com about how we met'], b:['📖','Have a bestselling novel written about us']},
    {e:'🤝', k:'What\u2019s something we survived together that made us stronger?', p:'IKEA furniture counts.'},
    {e:'🧩', k:'What did you learn about me that surprised you most?', p:'Good surprises and \u2018huh, okay\u2019 surprises both count.'},
    {e:'🎪', k:'What\u2019s the most spontaneous thing we\u2019ve ever done?', p:'Follow-up: should we do something like that again soon?'},
    {e:'🏆', k:'What\u2019s your proudest \u2018we did that\u2019 moment as a team?', p:'Big or small \u2014 pulling off a move counts as much as a wedding.'},
    {e:'🌊', k:'What\u2019s something you\u2019ve changed your mind about in the last few years?', p:'Big or small \u2014 from politics to pineapple on pizza.'},
    {kind:'choice', a:['🚐','A year traveling with only a backpack each'], b:['🏡','A year in our absolute dream home']},
    {e:'🧭', k:'What did you want to be when you were 8?', p:'Follow-up: what would 8-year-old you think of your life now?'},
    {e:'🎭', k:'What\u2019s something people assume about you that isn\u2019t true?', p:'Follow-up: do you ever play along with it?'},
    {e:'🌱', k:'What are you quietly working on becoming?', p:'Not a job title \u2014 a kind of person.'},
    {e:'🕰️', k:'What do you miss about being a kid?', p:'Follow-up: which part could we actually bring back?'},
    {e:'🎓', k:'What\u2019s the best advice anyone ever gave you?', p:'Follow-up: did you take it right away, or the hard way?'},
    {kind:'choice', a:['🧠','Know what I\u2019m thinking, always'], b:['🤫','Keep the mystery forever']},
    {e:'🌙', k:'What keeps you up at night lately \u2014 good or bad?', p:'Listen first. Fix later, only if asked.'},
    {e:'🪞', k:'What\u2019s something you\u2019re better at than you give yourself credit for?', p:'If they undersell it, the other person corrects the record.'},
    {e:'🕊️', k:'What\u2019s something you\u2019ve forgiven \u2014 or are still working on forgiving?', p:'Yourself counts. Skip is allowed, but try.'},
    {e:'🙏', k:'What\u2019s something I did recently that meant more than I probably realized?', p:'Little things count the most here.'},
    {e:'💎', k:'What quality of mine do you hope never changes?', p:'Then swap. No deflecting with a joke \u2014 okay, one joke.'},
    {kind:'choice', a:['🕺','Take dance lessons together'], b:['🧗','Take up rock climbing together']},
    {e:'☀️', k:'What was the best part of your week?', p:'Follow-up: what was the hardest part? Both deserve airtime.'},
    {e:'🫶', k:'How do you most feel loved \u2014 words, time, help, gifts, or touch?', p:'Follow-up: which one do you give the most? Are they the same?'},
    {e:'🌟', k:'Who\u2019s someone who shaped who you are \u2014 that I\u2019ve never met (or barely know)?', p:'Tell me their story in one minute.'},
    {e:'🏡', k:'What makes somewhere feel like home to you?', p:'A smell, a sound, a person, a chair?'},
    {e:'🍀', k:'What\u2019s something ordinary in your life you\u2019d genuinely miss if it vanished?', p:'Morning coffee, a commute podcast, this restaurant?'},
    {kind:'choice', a:['⏮️','Meet each other five years earlier'], b:['⏭️','Get one real glimpse of us ten years from now']},
    {e:'✈️', k:'Where in the world do you most want to go together?', p:'Dream big first \u2014 then name a trip we could actually do this year.'},
    {e:'🔮', k:'Where do you hope we are five years from now?', p:'Not just geography \u2014 what does a regular Tuesday look like?'},
    {e:'🎨', k:'What\u2019s something you\u2019ve always wanted to learn?', p:'Follow-up: what\u2019s actually stopping you? (Be honest.)'},
    {e:'🏝️', k:'Describe your perfect lazy day together.', p:'Hour by hour. Snacks must be specified.'},
    {e:'💰', k:'We just won the lottery. What\u2019s the first completely frivolous thing we buy?', p:'One each. No investing allowed for the first purchase.'},
    {kind:'choice', a:['🐶','Adopt an extremely dumb, extremely loving dog'], b:['🐈','Adopt a brilliant cat that judges us both']},
    {e:'📅', k:'What\u2019s one tiny tradition we should start?', p:'Weekly, monthly, or \u2018every time it rains.\u2019 Pick one and actually start it.'},
    {e:'🚀', k:'What\u2019s on your bucket list that I might not know about?', p:'Follow-up: which one could we knock out together first?'},
  ]},

];
